/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.10 */
package calculator;

public interface ParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTEXPR1 = 1;
  public int JJTEXPR2 = 2;
  public int JJTEXPR3 = 3;


  public String[] jjtNodeName = {
    "Expression",
    "Expr1",
    "Expr2",
    "Expr3",
  };
}
/* JavaCC - OriginalChecksum=fdffb8fff8df23e1bf00f93ac5159c76 (do not edit this line) */
